### ISSUE TITLE
Support for Multiple Facebook Sources

### ISSUE THREAD

**Issue by chrisnelson0** [michaelkamprath/multi-service-rtmp-broadcaster#10]
While I've not tested it, restream.io advertises multiple Facebook Page Outputs in their premium package.  Could we get something like that included?

**Comment by hoveeman** [comment]
I was thinking about this the other day, streaming to multiple Facebook pages, Youtube accounts, or custom urls. It would be easy enough to add additional environment variables for Facebook, Youtube, etc... but it may be a little clunky. I'd be happy to create that, but I'll let @michaelkamprath chime in if he would rather architect it in a different way.

**Comment by michaelkamprath** [comment]
@chrisnelson0 @hoveeman I do want to rethink the architecture a little before implementing this. I think the nginx configuration generation is a bit unwieldy and error prone. With that said, I will try to create a branch soon that you could use to do two facebook outputs, but I won't merge it into the main branch (meaning you'd need to build the docker image yourself).

**Comment by hoveeman** [comment]
That sounds like a good idea to rethink the architecture. I made my fork available on docker and I can add the messy implementation of 2x facebook pages, etc there. I'm also happy to work off your branch too. 

https://hub.docker.com/r/hovee/multistreaming-server

https://github.com/hoveeman/multi-service-rtmp-broadcaster

**Comment by michaelkamprath** [comment]
This is open source. You are welcome to fork and change as you desire (subject to the GPL v3 license, of course). With that said, I am working on a multi-key branch and will publish it soon.

**Comment by michaelkamprath** [comment]
@hoveeman @chrisnelson0 I finally got around to refactoring things to have a better architecture for handling multiple pushes to the same platform. Check out things in [the json-config branch](https://github.com/michaelkamprath/multi-service-rtmp-broadcaster/tree/json-config). As the name implies, you now use a JSON file to configure the rebroadcasting rather than a bunch of environment variables. I don't have it documented yet, but a JSON config would look something like this:

```
 {
  "endpoint": "live",
  "rebroacastList": [
    {
      "name": "facebook-1",
      "platform": "facebook",
      "streamKey": "abc123xxx"
    },
    {
      "name": "facebook-2",
      "platform": "facebook",
      "streamKey": "abc123xxx",
      "transcode": {
        "pixels": "640x480",
        "videoBitRate": "1500k"
      }
    },
    {
      "name": "youtube-1",
      "platform": "youtube",
      "streamKey": "abc123xxx"
    },
    {
      "name": "youtube-2",
      "platform": "youtube",
      "streamKey": "abc123xxx"
    },
    {
      "name": "periscope",
      "platform": "periscope",
      "streamKey": "abc123xxx",
      "transcode": {
        "pixels": "640x480",
        "videoBitRate": "1500k",
        "videoKeyFrameSecs": 3,
        "audioBitRate": "128k",
        "audioSampleRate": 44100
      }
    }
  ]
}
```
Notice how you can optionally set transcoding parameters. Also note that you can also have multiple pushes to the same platform. The only thing that has to be unique between the elements in the `rebroacastList` is the `name` of each element. If you have two rebroadcast elements with the same name, undefined things will happen.

To  launch the docker image after it is built:

**Comment by hoveeman** [comment]
Very cool! I’ll try and give it a test today and report back.
