### ISSUE TITLE
Question to run the server

### ISSUE THREAD

**Issue by carlosanpardo** [michaelkamprath/multi-service-rtmp-broadcaster#21]
Hello! Thank you for your effort in this project. 

In the wiki appear this command: 

docker run -it -p 80:80 -p 1935:1935 \
  --env MULTISTREAMING_PASSWORD=__made_up_password__ \
  -v /path/to/my-rtmp-config.json:/rtmp-configuation.json
  multistreaming-server:latest

But I can't understand the difference between /path/to/my-rtmp-config.json and rtmp-configuration.json.

Can you explain in detail please?

My rtmp-configuation.json is: 

```
{
  "endpoint": "live",
  "rebroacastList": [
    {
      "name": "youtube",
      "platform": "youtube",
      "streamKey": "Juds-wz22-urta-295k-a3ia"
    },
    {
      "name": "facebook",
      "platform": "facebook",
      "streamKey": "8798787878787?s_bl=1&s_ps=1&s_sw=0&s_vt=api-s&a=hdaASDASshsasda",
      "transcode": {
        "pixels": "1280x720",
        "videoBitRate": "4500k"
      }
    }
  ]
}
```

I appreciate your help.

**Comment by michaelkamprath** [comment]
What you are unfamiliar with is how a Docker container is launched, and more specifically, how you can bind a file or directory from outside the container to a file or directory within the container. I suggest that you go through one of the many multitude of Docker tutorials out there. With that said, the TL;DR is that in the `-v` option binds a file from outside the container, which is the file path to the config file on your computer and is on the left side of the `:`, to a "virtual file" within the container, which is the file path on the right of the `:` and is not something you can change as the container expect that file path to be `/rtmp-configuation.json`. 

If those details are confusing to you, then I suggest you use the `local-deploy.sh` script I wrote in the `deployment-scripts` directory. It takes care of the details of how to launch a Docker container for you. See the [README in the directory](https://github.com/michaelkamprath/multi-service-rtmp-broadcaster/blob/master/deployment-scripts/README.md) for more information. 

Finally, I very strongly suggest that you delete your configuration file above. Your stream keys should be kept very private. Since you made them public, anyone can stream to YouTube and Facebook and pretend to be you. I strongly suggest you generate new stream keys. Other than that, you configuration file

**Comment by carlosanpardo** [comment]
Thank you for your answer. I will learn more about Docker and check the file "local-deploy.sh" with the README.

About your message:
`Finally, I very strongly suggest that you delete your configuration file above. Your stream keys should be kept very private. Since you made them public, anyone can stream to YouTube and Facebook and pretend to be you. I strongly suggest you generate new stream keys. Other than that, you configuration file looks fine.`

Is not my credentials. I sent a fake info. Thank you!

**Comment by michaelkamprath** [comment]
Great! I am happy that you didn't send your actual credentials.  I will close this ticket. Feel free to reopen it or submit new one if you have more questions.
