### ISSUE TITLE
Feature - RTMP server via environment variables 

### ISSUE THREAD

**Issue by Nesslax** [michaelkamprath/multi-service-rtmp-broadcaster#28]
is it possible to be able to add environment variables  as input so when we run a docker command all RTMP outputs could be added/removed via a command line. 

Exemple: 
```
docker run -it -p 80:80 -p 1935:1935 \
  --env MULTISTREAMING_PASSWORD=__made_up_password__ \
  --env MULTISTREAMING_OUTPUT=__RTMP ADRESS/KEY__ \
  --env MULTISTREAMING_OUTPUT=__RTMP ADRESS/KEY__ \
  -v /path/to/my-rtmp-config.json:/rtmp-configuration.json
  multistreaming-server:latest
```

**Comment by michaelkamprath** [comment]
I'm not sure what you are asking. Are you asking to not use the JSON configuration file to set your rebroadcast destination and instead specify them on the docker command line (via environment variables)?

**Comment by Nesslax** [comment]
not necessarily one without the other but 
the environment variable is used to generate the JSON and with that, you can be flexible. 
PS : I have new keys for each livestream.

**Comment by michaelkamprath** [comment]
This whole project was designed around using the JSON configuration file to specify rebroadcast destinations because it gives you much richer flexibility in configuring the destination than can be easily obtained through command line variables. So, it is not possible with this project to accomplish what you want. The design paradigm see is to create multiple JSON configuration files if you want to predefine multiple configurations. In a world where you get a new stream key for every new broadcast, I can see that as being mildly annoying, but then editing a text file isn't that hard either. However, every major livestream platform has a "persistent stream key" option, which if used, wouldn't require you to edit your configuration file every time before a stream.

With that said, if you really design being able to configure your rebroadcast destinations on the command line, search around GitHub as there are plenty of other similar projects that took the environment variable approach to defining the rebroadcast destinations. You kind of give up the flexibility in configuring the details of the rebroadcast, most notably transcoding, but for straightforward use cases, it accomplishes the same thing.

**Comment by michaelkamprath** [comment]
Given the lack of response, I will close this issue. Please reopen if you have any further questions.
