### ISSUE TITLE
Ability to create multiple concurrent streams

### ISSUE THREAD

**Issue by Anil-matcha** [michaelkamprath/multi-service-rtmp-broadcaster#42]
Is it possible to use this to allow multiple users to stream to different destinations i.e a more dynamic platform where any user can enter and setup his keys and stream to various platforms instead of a fixed configuration for a single user.

Thanks in advance for the help

**Comment by michaelkamprath** [comment]
@Anil-matcha as it is currently set up, the answer is `no`. However, it wouldn't be hard to allow multiple simultaneous inbound streams each with different restreaming configurations. Pull requests are welcome!

**Comment by michaelkamprath** [comment]
One further comment: as currently set up, there is nothing to prevent you from running multiple differently cofigured docker containers on the same server. That is, each user gets their own container spun up. Note that you would have to remap the inbound ports so that each user has their own port for their stream.

My previous comment above was about have a single docker container serviing multiple inbound streams.

**Comment by Anil-matcha** [comment]
Thanks for responding @michaelkamprath . Each user can have their own docker container but wouldn't it be less efficient as ideally more users can be served in a single docker container instance ? So if 1000 users are streaming, spinning up 1000 containers feel less scalable

**Comment by michaelkamprath** [comment]
@Anil-matcha Closing this issue. Please feel free to reopen if more discussion is needed.
