### ISSUE TITLE
I am unable to get kick.com to work as a custom platform in the json config

### ISSUE THREAD

**Issue by successtheman** [michaelkamprath/multi-service-rtmp-broadcaster#46]
Below is the contents of my json config file with the stream keys removed, however when I try to start the docker container (I am using podman but it should not matter) it throws these errors (shown in the pastebin paste)

https://pastebin.com/QzsjAbwh

```
{
  "endpoint": "live",
  "transcodeProfiles": {
    "936_60fps": {
      "pixels": "1664x936",
      "videoBitRate": "6000k",
      "videoFrameRate": 60,
      "videoKeyFrameSecs": 2,
      "audioBitRate": "320k",
      "audioSampleRate": "48000"
    }
  },
  "rebroadcastList": [
    {
      "name": "twitch",
      "platform": "twitch",
      "streamKey": "STREAMKEY",
      "transcodeProfile": "936_60fps"
    },
    {
      "name": "kick",
      "platform": "custom",
      "fullRTMPURL": "rtmps://fa723fc1b171.global-contribute.live-video.net/STREAMKEY",
      "transcodeProfile": "936_60fps"
    }
  ]
}
```

**Comment by successtheman** [comment]
I am not sure if the kick URL should be the way I have it or `rtmps://fa723fc1b171.global-contribute.live-video.net/kick/streamkey` or `rtmps://fa723fc1b171.global-contribute.live-video.net/app/streamkey` I saw conflicting information on their discord server, but I have asked a question there to see if I can figure it out

**Comment by successtheman** [comment]
managed to get it working using this instead https://hub.docker.com/r/thiagoeolima/nginx-rtmps/

**Comment by successtheman** [comment]
For future reference the only format that worked was `rtmps://fa723fc1b171.global-contribute.live-video.net/kick/streamkey`

**Comment by michaelkamprath** [comment]
Glad you got things working for yourself. I haven't used this for a while myself, and it would seem Twitch has changed their URL format. With this project, you can always used the custom URL destination rather than the currently implemented twitch support as the code here currently uses the old (pre-2022?) twitch stream ingest. If I get time I will update things, but someone is always welcome to create a PR too, as this is open source after all.
